version: '3.8'

services:
  alexa-skill:
    build: .
    container_name: alexa-skill-container
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
